import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const satoshi = localFont({
  src: '../public/fonts/Satoshi-Variable.woff2',
})

const plusjakartasans = localFont({
  src: '../public/fonts/PlusJakartaSans-Variable.ttf',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className={`min-h-full flex flex-col ${plusjakartasans.className} bg-[#e5e5e5] p-8 md:p-12 lg:px-32 lg:py-12`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
